Repository MewsSystems/fiscalization-germany, pull requests merged in 2021-01, with the labels that each got.

#17 Automated assignment of tech.be and tech.review.qa projects
  .github/workflows/pr-automation-tech-be-assign.yml
  .github/workflows/pr-automation-tech-review-qa-assign.yml
  .github/workflows/pr-automation-tech-review-qa-move-on-close.yml
Labels: dev-tested, finance

#18 Updated to latest version of core library.
  .github/workflows/build-and-test.yml
  .github/workflows/publish.yml
  src/Mews.Fiscalization.Germany.Tests/Mews.Fiscalization.Germany.Tests.csproj
  src/Mews.Fiscalization.Germany.Tests/TestFixture.cs
  src/Mews.Fiscalization.Germany/Mews.Fiscalization.Germany.csproj
  src/Mews.Fiscalization.Germany/Model/Types/ApiKey.cs
  src/Mews.Fiscalization.Germany/Model/Types/ApiSecret.cs
Labels: finance

#19 Default to bash shell instead of cli.
  .github/workflows/publish.yml
Labels: finance

#20 Updated Core lib NuGet.
  src/Mews.Fiscalization.Germany/Mews.Fiscalization.Germany.csproj
Labels: easyfix, finance
